version: "3"

services:
  backend:
    container_name: "kupipodariday-backend"
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: ./.env
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    container_name: "kupipodariday-database"
    image: postgres:12.12-alpine
    restart: on-failure
    env_file: ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: "kupipodariday-frontend"
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - backend
volumes:
  pgdata:
